src/Entity/Student.php
<?php

namespace App\Entity;

use App\Entity\Session;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\StudentRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10)]
    private ?string $sexe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]

    #[Assert\NotBlank(message: 'Please select a birthdate')]
    #[Assert\GreaterThanOrEqual(
        "today",
        message: 'Date must be greater than or equal to current date.'
    )]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(length: 100)]
    private ?string $firstName = null;

    #[ORM\Column(length: 100)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 50)]
    private ?string $phoneNumber = null;

    #[ORM\Column(length: 100)]
    private ?string $city = null;

    #[ORM\ManyToMany(targetEntity: Session::class, inversedBy: 'students')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): static
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAge():  string
    {
        $now = new \DateTime();
        $interval = $this->birthday->diff($now);
        return $interval->format("%Y");
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): static
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getFormattedPhoneNumber(): ?string
    {
        $phoneNumber = $this->phoneNumber;

        // Vérifier si le numéro de téléphone est vide
        if (empty($phoneNumber)) {
            return null;
        }

        // Supprimer les caractères non numériques
        $phoneNumber = preg_replace('/[^0-9]/', '', $phoneNumber);

        // Formater le numéro de téléphone
        $formattedPhoneNumber = vsprintf('%s.%s.%s.%s.%s', str_split($phoneNumber, 2));

        return $formattedPhoneNumber;
    }


    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        $this->sessions->removeElement($session);

        return $this;
    }

    public function __toString() {
        
        return $this->lastName. " " .$this->firstName;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Student;
use App\Form\ProgrammeType;
use App\Entity\ModuleFormation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;



class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sexe' , TextType::class)
            ->add('birthday', DateType::class, [
                'widget' => 'single_text',
                
            ])
            ->add('firstName' , TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'First name',
                ]
            ])
            ->add('lastName' , TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Last name',
                ]
            ])
            ->add('email' , EmailType::class)
            ->add('phoneNumber' , TextType::class)
            ->add('city' , TextType::class)
            ->add('Validate', SubmitType::class, [
                'attr' => [
                    'class' => 'btn-submit'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use Knp\Snappy\Pdf;
use App\Entity\Session;
use App\Entity\Student;
use App\Form\StudentType;
use App\Service\ValidationService;
use App\Repository\SessionRepository;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class StudentController extends AbstractController
{
    #[Route('/student', name: 'app_student')]
    public function index(StudentRepository $studentRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $students = $studentRepository->findBy([], ["lastName" => "ASC"]);

        $pagination = $paginator->paginate(
            $students, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );



        return $this->render('student/index.html.twig', [
            'students' => $students,
            'pagination' => $pagination
        ]);
    }

    #[Route('/student/new', name: 'new_student')]
    #[Route('/student/{id}/edit', name: 'edit_student')]
    public function new_edit(Student $student = null, Request $request, EntityManagerInterface $entityManager) : Response
    {

        if(!$student) {
            $student = new Student();
        }

        $form = $this->createForm(StudentType::class, $student);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $student = $form->getData();
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('app_student');
        }

        return $this->render('student/new.html.twig', [
            'formAddStudent' => $form,
            'edit' => $student->getId()
        ]);

    }

    #[Route('/student/{id}/delete', name: 'delete_student')]
    public function delete(Student $student, EntityManagerInterface $entityManager) : Response {

        // remove: enlève de la collection l'employé ciblé
        // flush : fait la requête SQl auprès de la BD
        $entityManager->remove($student);
        $entityManager->flush();

        return $this->redirectToRoute('app_student');
    }


    
    // on nomme l'id id pour utiliser le paramConverter - faire le lien avec l'object qu'on souhaite facilement
     #[Route('/student/{id}', name: 'show_student')]
     public function show(SessionRepository $sessionRepository, Student $student = null): Response
    {

        $currentSessions = $sessionRepository->findCurrentSessions($student, null);
        $upcomingSessions = $sessionRepository->findUpcomingSessions($student, null);
        $pastSessions = $sessionRepository->findPastSessions($student, null);

        // dump($currentSessions, $upcomingSessions, $pastSessions);die;
        if (!$student) {
            // L'entité Student avec cet ID n'existe pas, redirigez vers la page d'accueil ou une autre page.
            return $this->redirectToRoute('app_home');
        }

        return $this->render('student/show.html.twig', [
            'student' => $student,
            'currentSessions' => $currentSessions,
            'upcomingSessions' => $upcomingSessions,
            'pastSessions' => $pastSessions,
        ]);
    }

    
    public function listAction(EntityManagerInterface $em, PaginatorInterface $paginator, Request $request)
    {
        $dql   = "SELECT a FROM AcmeMainBundle:Article a";
        $query = $em->createQuery($dql);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3 /*limit per page*/
        );

        // parameters to template
        return $this->render('article/list.html.twig', ['pagination' => $pagination]);
    }



    
}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Students' list{% endblock %}

{% block body %}

    <div class="main-content-page student-index-page">

        <div id="title-add">
            <h1>Students List</h1>

            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('new_student') }}" ><i class="fa-solid fa-user-plus"></i></a>
            {% endif %}

        </div>
        
        <div id="top">
            
            <p>Name</p>
            <p>Training Session</p>
            <p>Starting Date</p>
            <p>Ending Date</p>
            <p>Status</p>
            
        </div>
   

        <div class="session-list" id="student-list"> 
        
                {% for student in pagination %}
                    <div class="list-ind-student">
                        
                    {# <p>{{student.sessions.formation.name}}</p> #}
                    
                    {% for session in student.sessions %}
                    {% set currentDate = date('now') %}
                        <p><a href="{{ path('show_student', {'id': student.id }) }}">{{student}}</a></p>
                        <p><a href="{{ path('show_session', {'id': session.id }) }}">{{session.formation.name}}</a></p>


                        <p>{{session.startDate|date("d.m.Y")}}</p>
                        <p>{{session.endDate|date("d.m.Y")}}</p>
                        
                        
                            {% set currentDate = date('now') %}
                            {% if session.startDate <= currentDate and currentDate <= session.endDate %}
                                <p class="status-btn started">started</p>
                                
                            {% elseif session.startDate > currentDate %}                           
                                <p class="status-btn not-started">not started</p>
                            
                            {% elseif session.endDate < currentDate %}
                                <p>error</p>
                            {% endif %}
                        
                    {% endfor %}
    
                        {# <a  href="{{ path('edit_student', {'id': student.id }) }}">Edit</a>
                        <a  href="{{ path('delete_student', {'id': student.id }) }}">Supprimer</a>  #}
                    </div>
                    <div class="line"></div>
                {% endfor %}
            
              
        </div>

        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>

    </div>

    </div>

     {% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a student{% endblock %}

{% block body %}

    <div class="main-content-page student-new-page">

        <div id="title-add">
            {% if edit %}
            <h1>Edit a student</h1>
            {% else %}
            <h1>Add a student</h1>
            {% endif %}
        </div>

        <div id="form-student">

            <div id="header-top"></div>
            {{ form_start(formAddStudent) }}
            <div id="name-student-form">
                <i class="fa-solid fa-user-plus"></i>
                <p>NAME :</p>
                <div class="last-first-name">{{ form_row(formAddStudent.lastName) }} {{ form_row(formAddStudent.firstName) }}</div>
            </div>
            
            <div id="back-left"></div>
            <div id="back-right"></div>
            
            <div id="inputs-form-student">
                <div>
                    <div>
                        {{ form_label(formAddStudent.sexe) }}
                        {{ form_widget(formAddStudent.sexe) }}
                    </div>
                    <div>
                        
                        {{ form_row(formAddStudent.birthday) }}
                    </div>
                    
                </div>
                
                    <div>
                        {{ form_row(formAddStudent.email) }}
                        {{ form_row(formAddStudent.phoneNumber) }}
                    </div>            
                
                    <div>  {{ form_row(formAddStudent.city) }}</div>

                </div>
                
                <div id="submit-btn-form">
                    {{ form_row(formAddStudent.Validate) }}
                </div>
                
            {{ form_end(formAddStudent) }}

        </div>
    
        
    </div> 
    {% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un stagiaire{% endblock %}

{% block body %}

    <div class="main-content-page student-index-page">
  
        <div id="title-add">
            <h1>Detail student</h1>
        </div>

        <div id="top">
            <p>{{ student}}</p>
            <p><a href="{{ path('app_pdf_generator', {'id': student.id}) }}"><i class="fa-solid fa-file-pdf fa-xl"></i></a></p>
            
        </div>


        <div class="module-areas">

            <div class="module-area detail-session ">
                <div class="top">
                    
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('edit_student', {'id': student.id }) }}"><i class="ri-file-edit-fill"></i></a>
                        <a href="#"<i id="delete-student-popup" class="ri-close-circle-fill"></i></a><br>
                    {% endif %}
                </div>


                <div class="confirm-delete" style="display:none">
                    <div>
                        <p>Are you sure you want to delete this student, this action can't be undone</p>
                        <div id="actions">
                            
                            <a href="{{ path('delete_student', {'id': student.id }) }}"><p> <span id="confirm-delete"><i class="ri-checkbox-circle-fill"></i></span>confirm</p></a>
                            <a  id="cancel-delete" href="#"><p><span><i class="ri-close-circle-fill"></i></span>cancel</p></a>
                            
                        </div>
                    </div>
                </div>


                <div class="content">
                    <p> <span>Name : </span>{{ student}}</p>
                    <p> <span>Gender : </span> {{student.sexe}} </p>
                    <p> <span>Mail : </span> {{student.email}}</p>
                    <p> <span>Phone : </span>  {{student.FormattedPhoneNumber}}</p>
                    <p> <span>City : </span> {{student.city}}  </p>
                    <p> <span>Birthday : </span>  {{student.birthday|date("d.m.Y")}}</p>
                    <p><span>Age : </span>{{ student.age}}  years old</p>
                </div>
            </div>



           

            <div class="module-area student-session ">
                <div class="top">
                    <p>Student session/s list</p>
                </div>

                <div class="content">
                   <div class="current">
                        <p>Current session :</p>
                        

                            {% if currentSessions | length > 0 %}
                                {% for session in currentSessions  %}
                                    <div>
                                        <p>•<a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></p>
                                        <p>{{session.startDate|date("d.m.Y")}}</p>
                                        <p>{{session.endDate|date("d.m.Y")}}</p>
                                        
                                    </div>
                                {% endfor %}   
                            {% else %}
                                <p>No current session.</p>
                            {% endif %}
                   </div>

                   <div class="upcoming">
                        <p>Upcoming session/s :</p>

                        {% if upcomingSessions | length > 0 %}
                            {% for session in upcomingSessions  %}
                                <div>
                                    <p>•<a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></p>
                                    <p>{{session.startDate|date("d.m.Y")}}</p>
                                    <p>{{session.endDate|date("d.m.Y")}}</p>
                                    
                                </div>
                            {% endfor %}   
                        {% else %}
                            <p class="text">No upcoming session.</p>
                        {% endif %}
                   </div>

                   <div class="past">
                        <p>Past session/s : </p>

                        {% if pastSessions | length > 0 %}
                            {% for session in pastSessions  %}
                                <div>
                                    <p>•<a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></p>
                                    <p>{{session.startDate|date("d.m.Y")}}</p>
                                    <p>{{session.endDate|date("d.m.Y")}}</p>
                                    
                                </div>
                            {% endfor %}   
                        {% else %}
                            <p class="text">No past session.</p>
                        {% endif %}

                   </div>
                </div>
            </div>

        
            
      

{% endblock %}