src/Entity/Session.php
<?php

namespace App\Entity;

// use Assert\LessThan;
use App\Entity\Student;
use App\Entity\Formation;
use App\Entity\Programme;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SessionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank (message: "Please select a starting date")]
    #[Assert\GreaterThanOrEqual(
        "today",
        message : 'The selected date must be greater than or equal to the current date.'
    )]
    #[Assert\When(
        expression: 'this.getEndDate() !=null',
        constraints: [
            new Assert\LessThan(
                propertyPath: 'endDate',
                message: 'The selected end date must be later than the start date.'
            )
        ]
    )]
    private ?\DateTimeInterface $startDate = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: 'Please select an ending date')]
    #[Assert\When(
        expression: 'this.getStartDate() != null',
        constraints: [
            new Assert\GreaterThan(
                propertyPath: 'startDate',
                message: 'The selected start date must be earlier than the end date.'
            )
        ]
    )]
    private ?\DateTimeInterface $endDate = null;


    #[ORM\Column]
    #[Assert\GreaterThan(value: 0, message: 'The value must be greater than 0')]
    private ?int $nbPlaceTotal = null;
    

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Programme::class, orphanRemoval: true)]
    private Collection $programmes;

    #[ORM\ManyToMany(targetEntity: Student::class, mappedBy: 'sessions')]
    private Collection $students;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $formation = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 120)]
    private ?string $name = null;

    public function __construct()
    {
        $this->programmes = new ArrayCollection();
        $this->students = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getNbPlaceTotal(): ?int
    {
        return $this->nbPlaceTotal;
    }

    public function setNbPlaceTotal(int $nbPlaceTotal): static
    {
        $this->nbPlaceTotal = $nbPlaceTotal;

        return $this;
    }


    public function getNbPlacebooked(): ?int {
        return count($this->students);
    }
 
    public function getNbPlaceRemaining(): ?int {
        return $this->nbPlaceTotal - count($this->students);
    }
 

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Student>
     */
    public function getStudents(): Collection
    {
        return $this->students;
    }

    public function addStudent(Student $student): static
    {
        if (!$this->students->contains($student)) {
            $this->students->add($student);
            $student->addSession($this);
        }

        return $this;
    }

    public function removeStudent(Student $student): static
    {
        if ($this->students->removeElement($student)) {
            $student->removeSession($this);
        }

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

 

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function __toString() {
        
        return $this->name;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Session;
use App\Entity\Formation;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // ->add('formation' , TextType::class)

            ->add('formation', EntityType::class, [
                'class' => Formation::class,
                'attr' => ['class' => 'custom-dropdown'],
            ])

            ->add('name', TextType::class)
            ->add('startDate' , DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('endDate' , DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('nbPlaceTotal' , IntegerType::class, [
                'label' => 'Number of places',
            ])

         
            ->add('user', EntityType::class, [
                'class' => User::class,
                'label' => 'Main teacher',
            ])

            

            ->add('Validate', SubmitType::class, [
                'attr' => [
                    'class' => 'btn-submit'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php
 namespace App\Controller;

use App\Service\ValidationService;
use App\Entity\Session;
use App\Entity\Student;
use App\Entity\Programme;
use App\Form\SessionType;
use App\Form\StudentType;
use App\Form\ProgrammeType;
use App\Entity\ModuleFormation;
use App\Form\StudentSessionType;
use App\Repository\SessionRepository;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;
 
 
class SessionController extends AbstractController
{
 




    #[Route('/session', name: 'app_session')]
    public function index(SessionRepository $sessionRepository,Request $request, PaginatorInterface $paginator): Response
    {
        $sessions = $sessionRepository->findBy([], ["endDate" => "ASC"]);

        $currentSessions = $sessionRepository->findCurrentSessions();
        $upcomingSessions = $sessionRepository->findUpcomingSessions();
        $pastSessions = $sessionRepository->findPastSessions();
        // dd($pastSessions);
        

        // Vérifier si la demande est une requête AJAX
        if ($request->isXmlHttpRequest()) {
            // Si oui, renvoyer uniquement les futures sessions en format JSON
            $pastSessionsData = [];
            foreach ($pastSessions as $session) {
                $pastSessionsData[] = [
                    'id' => $session->getId(),
                    // 'nom' => $session->getNom(),
                    
                ];
            }

            return new JsonResponse($pastSessionsData);
        }


        return $this->render('session/index.html.twig', [
            // 'controller_name' => 'SessionController',
            'sessions' => $sessions,
            'currentSessions' => $currentSessions,
            'upcomingSessions' => $upcomingSessions,
            'pastSessions' => $pastSessions,
        ]);
    }
 
    #[Route('/session/new', name: 'new_session')]
    #[Route('/session/{id}/edit', name: 'edit_session')]
    public function new_edit(Session $session = null, Request $request, EntityManagerInterface $entityManager): Response
    {
 
        if (!$session) {
            $session = new session();
        }
 
        $form = $this->createForm(SessionType::class, $session);
 
        $form->handleRequest($request);
 
        if ($form->isSubmitted() && $form->isValid()) {
 
            $session = $form->getData();
            $entityManager->persist($session);
            $entityManager->flush();
 
            return $this->redirectToRoute('app_session');
        }
 
        return $this->render('session/new.html.twig', [
            'formAddSession' => $form,
            'edit' => $session->getId()
        ]);
 
    }
 
 
    #[Route('/session/{id}/delete', name: 'delete_session')]
    public function delete(Session $session, EntityManagerInterface $entityManager): Response
    {
 
        // remove: enlève de la collection l'employé ciblé
        // flush : fait la requête SQl auprès de la BD
        $entityManager->remove($session);
        $entityManager->flush();
 
        return $this->redirectToRoute('app_session');
    }
 

 
    #[Route('/session/{id}', name: 'show_session')]
    public function show($id, ValidationService $validationService, Session $session = null, Request $request, EntityManagerInterface $entityManager, SessionRepository $sr): Response
    {
 
        $entityClassName = "App\Entity\Session";

        if (!$validationService->isValidId($id, $entityClassName)) {
            // Redirection vers une autre page si l'ID n'est pas valide
            return $this->redirectToRoute('app_home'); 
        }


        //^ Form to add Module
        $programme = new Programme();
        $programme->setSession($session);

        $noneAddedModules = $sr->findNoneAdded($session->getId());
 

        $form = $this->createForm(ProgrammeType::class, $programme, ['modules' => $noneAddedModules]);
        $form->handleRequest($request);
 
        if ($form->isSubmitted() && $form->isValid()) {
            $programme = $form->getData();
            $entityManager->persist($programme);
            $entityManager->flush();
            return $this->redirectToRoute('show_session', ['id' => $programme->getSession()->getId()]);
        }
 
        
        $noneRegisteredStudents = $sr->findNoneRegistered($session->getId());
        // dd($noneAddedModules);
        
 
        return $this->render('session/show.html.twig', [
            'session' => $session,
            'formAddProgramme' => $form,
            'noneRegisteredStudents' => $noneRegisteredStudents,
            'noneAddedModules' => $noneAddedModules,
            'edit' => $programme->getId()
        ]);
    }


    #[Route('/session/{session}/delete/{student}', name: 'remove_student_from_session')]
    public function removeStudent(Session $session, Student $student, EntityManagerInterface $entityManager): Response
    {
        // $session = $entityManager->find(Session::class, $id);
        // $student = $entityManager->find(Student::class, $studentId);
    
       
        // if ($session && $student) {
            $session->removeStudent($student);
            $entityManager->flush();
        // }
    

    return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }


    #[Route('/session/{session}/add/{student}', name: 'add_student_from_session')]
    public function addStudent(Session $session, Student $student, EntityManagerInterface $entityManager): Response
    {
        // $session = $entityManager->find(Session::class, $id);
        // $student = $entityManager->find(Student::class, $studentId);

        // if ($session && $student) {
            $session->addStudent($student);
            $entityManager->flush();
        // }
    

    return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }

}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Training sessions list{% endblock %}

{% block body %}

    <div class="main-content-page session-index-page">

        <div id="title-add">
            <h1>Training Sessions</h1>

            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('new_session') }}" ><i class="fa-regular fa-calendar-plus"></i></a>
            {% endif %}

        </div>
        
        <div id="top">
            <p>Session's Title</p>
            <p>Starting Date</p>
            <p>Ending Date</p>
            <p>Places</p>
            <p>Remaining Places</p>
            <p>Detail</p>
        </div>

        <div class="session-top" id="current-session-top">

            <h2>Current Sessions</h2>
            <i id="currentUpBtn" class="fa-solid fa-chevron-up"></i>
        </div>

        <div class="session-list" id="current-session-list">
            {% for session in currentSessions  %}
                    <div>
                        <h3><a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></h3>
                        <p>{{session.startDate|date("d.m.Y")}}</p>
                        <p>{{session.endDate|date("d.m.Y")}}</p>
                        <p>{{ session.nbPlacebooked }} / {{session.nbPlaceTotal}}</p>
                        <p>{{ session.nbPlaceRemaining }}</p>
                        <p><a href="{{ path('show_session', {'id': session.id }) }}"> <i class="ri-git-repository-commits-fill"></i></a></p>
                    </div>
            {% endfor %}                    
        </div>

        <div class="session-top" id="upcoming-session-top">
            <h2>Upcoming Sessions</h2>
            <i id="upcomingUpBtn" class="fa-solid fa-chevron-up"></i>
        </div>

        <div class="session-list" id="upcoming-session-list">
            {% for session in upcomingSessions %}
                <div>
                    <h3> <a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></h3>
                    <p>{{session.startDate|date("d.m.Y")}}</p>
                    <p>{{session.endDate|date("d.m.Y")}}</p>
                    <p>{{ session.nbPlacebooked }} / {{session.nbPlaceTotal}} </p>
                    <p>{{ session.nbPlaceRemaining }}</p>
                    <p><a href="{{ path('show_session', {'id': session.id }) }}"> <i class="ri-git-repository-commits-fill"></i></a></p>
                </div>
            {% endfor %}
        </div>

        <div id="show-past-sessions-btn">
            <p>Show past sessions</p>
        </div>
      
        <div id="past-sessions-container" style="display:none">

            <div class="session-top" id="past-session-top">
                <h2>Past Sessions</h2>
                
            </div>

            <div class="session-list" id="past-session-list">

                {% for session in pastSessions %}
                    <div>
                        <h3> <a href="{{ path('show_session', {'id': session.id }) }}"> {{session}}</a></h3>
                        <p>{{session.startDate|date("d.m.Y")}}</p>
                        <p>{{session.startDate|date("d.m.Y")}}</p>
                        <p>{{ session.nbPlacebooked }} / {{session.nbPlaceTotal}} </p>
                        <p></p>
                        <p></p>
                    </div>
                {% endfor %}
            </div>
        </div>


    </div>


{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add/edit a Session{% endblock %}

{% block body %}

<div class="main-content-page session-new-page">

    {# {{ form(formAddEmploye) }} #}
    <div id="title-add">

        {% if edit %}
        <h1>Edit a session</h1>
        {% else %}
        <h1>Add a session</h1>
        {% endif %}


    </div>
    
    <div id="form-student">

        <div id="header-top"></div>

        {{ form_start(formAddSession) }}
            {{ form_errors(formAddSession) }}

            <div id="name-student-form">
                <i class="ri-calendar-2-line"></i>
                <p>NAME :</p>
                <div class="last-first-name">{{ form_row(formAddSession.name) }}</div>
            </div>

            <div id="back-left"></div>


            <div id="inputs-form-student">

                <div>
                    <div>
                        {{ form_row(formAddSession.formation) }}
                    </div>
                    <div>
                        {{ form_row(formAddSession.nbPlaceTotal) }}
                    </div>
                </div>

                <div>
                    <div>
                        {{ form_row(formAddSession.startDate) }}
                    </div>
                    <div>
                        {{ form_row(formAddSession.endDate) }}
                    </div>
                </div>

                {{ form_row(formAddSession.user) }}

            </div>
   
            <div id="submit-btn-form">
                {{ form_row(formAddSession.Validate) }}
            </div>
        
            
        
        {{ form_end(formAddSession) }}


    </div>
    


</div>


{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail session{% endblock %}

{% block body %}

    <div class="main-content-page session-index-page session-detail-page">

        <div id="title-add">
            <h1>Detail session</h1>
        </div>

        <div id="top">
            <p>{{ session}}</p>
        </div>

        <div class="module-areas">

            <div class="module-area detail-session ">
                <div class="top">
                    
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('edit_session', {'id': session.id }) }}"><i class="ri-file-edit-fill"></i></a>
                        <a href="{{ path('delete_session', {'id': session.id }) }}"><i class="ri-close-circle-fill"></i></a><br>
                    {% endif %}
                </div>
                <div class="content">
                    <p> <span>Formation:</span> {{ session.formation}}</p>
                    <p> <span>Date:</span> {{session.startDate|date("d.m.Y")}} - {{session.endDate|date("d.m.Y")}} </p>
                    <p> <span>Number of places :</span> {{ session.nbPlaceTotal}}</p>
                    <p> <span>Number of students registered:</span> {{ session.nbPlacebooked }}</p>
                    <p> <span>Number of remaining places:</span> {{ session.nbPlaceRemaining }} </p>
                    <p> <span>Main teacher:</span> <a href="{{ path('show_teacher', {'id': session.user.id}) }}">{{session.user}}</a></p>
                </div>
            </div>

     

            <div id="student-session" class="module-area student-session ">
                <div class="top">
                    <p>Students registered</p>
                    <p>Action</p>
                </div>

                <div class="content">
                    {% if session.students| length > 0 %}
    
                        {% for student in session.students %}

                        <div>
                            <a href="{{ path('show_student', {'id': student.id }) }}">• <span>{{student}}</span></a>
                            <a href="{{ path('remove_student_from_session', {'session': session.id, 'student': student.id}) }}"><i class="ri-close-circle-line"></i></a>

                        </div>
                            
       
                        {% endfor %}
                    {% else %}
                            <p>No students registered.</p>
                    {% endif %}
                </div>

                <div class="add-el" id="add-student-btn">
                    <p>Add a student</p>
                </div>


            </div>

            <div id="module-session" class="module-area module-session ">
                <div class="top">
                    <p>Module</p>
                    {# <p>Duration</p> #}
                    <p>Action</p>
                </div>

                <div class="content">
                    
                    {% if session.programmes| length > 0 %}

                    {% for programme in session.programmes %}
                    <div>
                        • {{programme.ModuleFormation.name}} ( {{programme.duration}} days) 
                        <a href="{{ path('delete_programme', {'id': programme.id}) }}"><i class="ri-close-circle-line"></i></a>
                    </div>   
                        {% endfor %}
                    {% else %}
                        <p>Aucun module .</p>
                    {% endif %}
                </div>

                <div class="add-el" id="add-module-btn">
                    <p>Add a module</p>
                </div>
            </div>


            <div class="module-area add-student" style="display:none">

                <div class="top">
                    <p>Students</p>
                    <p>Action</p>
                </div>

                <div class="content">
                    {% if session.nbPlaceRemaining <= 0 %}
                        <p>No more availaible places.</p>
                    {% else %}
                        {% for student in noneRegisteredStudents %}
                        <div>
                            <a href="{{ path('show_student', {'id': student.id }) }}">{{ student }}</a>
                            <a href="{{ path('add_student_from_session', {'session': session.id, 'student': student.id}) }}"><i class="ri-add-circle-line"></i></a>

                        </div>
                           
                        {% endfor %}
                    {% endif %}
                </div>

            </div>

            <div class="module-area add-module " style="display:none">
                <div class="content">

                    {{ form_start(formAddProgramme) }}
                        {{ form_errors(formAddProgramme) }}
            
                        {% for module in formAddProgramme.moduleFormation %}
                          
                            <p> {{ form_row(module.duration) }}</p>
                            <p>{{ form_row(module.moduleFormation) }}</p>

                        <div id="submit-btn-form">
                            {{ form_row(module.Validate) }}
                        </div>
                       
                        {% endfor %}
                       
                    {{ form_end(formAddProgramme) }}
                </div>
            </div>

        </div>


        
    </div>


{% endblock %}